// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3fve1hBP0s5DeO3AbKjpXdrA-X84cnIk',
    appId: '1:1007266249669:web:8751d739203e93531829ac',
    messagingSenderId: '1007266249669',
    projectId: 'asiaroboticamovil',
    authDomain: 'asiaroboticamovil.firebaseapp.com',
    storageBucket: 'asiaroboticamovil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMy00D5kKAdKTkbRAqWm3YLTZH6OVXlY',
    appId: '1:1007266249669:android:d865c47e5d37493c1829ac',
    messagingSenderId: '1007266249669',
    projectId: 'asiaroboticamovil',
    storageBucket: 'asiaroboticamovil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGaLFjmcC8Q7ITqFNW638rniZiE9pQOE',
    appId: '1:1007266249669:ios:3a736ac56ab4ed161829ac',
    messagingSenderId: '1007266249669',
    projectId: 'asiaroboticamovil',
    storageBucket: 'asiaroboticamovil.appspot.com',
    androidClientId: '1007266249669-o111e017rgk25mp6qvnc76kamiq6ja09.apps.googleusercontent.com',
    iosClientId: '1007266249669-4vhvqfjuuu712jlds0ouiat88vh9fc8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.transferenciaMaterial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGaLFjmcC8Q7ITqFNW638rniZiE9pQOE',
    appId: '1:1007266249669:ios:d79b3e2c7b8d82811829ac',
    messagingSenderId: '1007266249669',
    projectId: 'asiaroboticamovil',
    storageBucket: 'asiaroboticamovil.appspot.com',
    androidClientId: '1007266249669-o111e017rgk25mp6qvnc76kamiq6ja09.apps.googleusercontent.com',
    iosClientId: '1007266249669-f9ec7rs7hutdnntj1dit4thgkrbh31aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.transferenciaMaterial.RunnerTests',
  );
}
