// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqb_T4gObbYB3NonTw7Qk3GQ0nxF9BzA',
    appId: '1:975620703335:web:65d24d89cf31af6db680c2',
    messagingSenderId: '975620703335',
    projectId: 'loginfirebase-9d539',
    authDomain: 'loginfirebase-9d539.firebaseapp.com',
    databaseURL: 'https://loginfirebase-9d539-default-rtdb.firebaseio.com',
    storageBucket: 'loginfirebase-9d539.appspot.com',
    measurementId: 'G-J11XTE1H2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWp9j3GIBD-FAVhQt03A2mxgrueZGW-_Q',
    appId: '1:975620703335:android:1a80dc9744f00b56b680c2',
    messagingSenderId: '975620703335',
    projectId: 'loginfirebase-9d539',
    databaseURL: 'https://loginfirebase-9d539-default-rtdb.firebaseio.com',
    storageBucket: 'loginfirebase-9d539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDA6C2n9_ERH4qELjoSzp4fFQNC-WNQCU',
    appId: '1:975620703335:ios:98f99afa35ed2111b680c2',
    messagingSenderId: '975620703335',
    projectId: 'loginfirebase-9d539',
    databaseURL: 'https://loginfirebase-9d539-default-rtdb.firebaseio.com',
    storageBucket: 'loginfirebase-9d539.appspot.com',
    iosClientId: '975620703335-ett2m0tf7dkno272fmgtoaqa0ktaprv8.apps.googleusercontent.com',
    iosBundleId: 'com.clientesasiarobotica.asiarobotica.appClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDA6C2n9_ERH4qELjoSzp4fFQNC-WNQCU',
    appId: '1:975620703335:ios:dda25fe428fb0e30b680c2',
    messagingSenderId: '975620703335',
    projectId: 'loginfirebase-9d539',
    databaseURL: 'https://loginfirebase-9d539-default-rtdb.firebaseio.com',
    storageBucket: 'loginfirebase-9d539.appspot.com',
    iosClientId: '975620703335-o0htbvep4u1ac8fv884mb2klathtfi57.apps.googleusercontent.com',
    iosBundleId: 'com.clientesasiarobotica.asiarobotica.appClientes.RunnerTests',
  );
}
