// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYH69V4GeIl-dczol4BLQ6RagQA4mspU',
    appId: '1:691963050021:web:76df98e712a7ef2a4767cc',
    messagingSenderId: '691963050021',
    projectId: 'logistica-ar',
    authDomain: 'logistica-ar.firebaseapp.com',
    storageBucket: 'logistica-ar.appspot.com',
    measurementId: 'G-7QYE1NFSKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUyUFl5I70UHUb4NxVM0UGEkhqPZ_ms0',
    appId: '1:691963050021:android:d6d7cbc1522cd4de4767cc',
    messagingSenderId: '691963050021',
    projectId: 'logistica-ar',
    storageBucket: 'logistica-ar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TQly6BHaEhvYddZFyHQwKA0bt34mr0o',
    appId: '1:691963050021:ios:9de59b7023ccbf404767cc',
    messagingSenderId: '691963050021',
    projectId: 'logistica-ar',
    storageBucket: 'logistica-ar.appspot.com',
    iosClientId: '691963050021-r88d27g1pm74dpqf275rsv30tmuft9ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.entregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TQly6BHaEhvYddZFyHQwKA0bt34mr0o',
    appId: '1:691963050021:ios:d6f952fa3f784f304767cc',
    messagingSenderId: '691963050021',
    projectId: 'logistica-ar',
    storageBucket: 'logistica-ar.appspot.com',
    iosClientId: '691963050021-u4vjhcqtm88do5b7g288er0q736qj7ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.entregas.RunnerTests',
  );
}
