// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZM5nSY7CshCE-Zc3eaUQ8pxv5MswdA0',
    appId: '1:743911311320:web:06c5feda45a9fba18154ad',
    messagingSenderId: '743911311320',
    projectId: 'vehiculos-ar',
    authDomain: 'vehiculos-ar.firebaseapp.com',
    storageBucket: 'vehiculos-ar.appspot.com',
    measurementId: 'G-VX6G5NB913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVbRjfxNkntxAn8c6mOPS1eNGfvDHkmx8',
    appId: '1:743911311320:android:b92ffad701a1ed378154ad',
    messagingSenderId: '743911311320',
    projectId: 'vehiculos-ar',
    storageBucket: 'vehiculos-ar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zDddRyki7J1-NqSv8vdgpzRrd-y5cOE',
    appId: '1:743911311320:ios:2a9948f7bac463d98154ad',
    messagingSenderId: '743911311320',
    projectId: 'vehiculos-ar',
    storageBucket: 'vehiculos-ar.appspot.com',
    iosBundleId: 'com.example.vehiculos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2zDddRyki7J1-NqSv8vdgpzRrd-y5cOE',
    appId: '1:743911311320:ios:dff5d452f9c6e7ba8154ad',
    messagingSenderId: '743911311320',
    projectId: 'vehiculos-ar',
    storageBucket: 'vehiculos-ar.appspot.com',
    iosBundleId: 'com.example.vehiculos.RunnerTests',
  );
}
